key: demographics
scorable: false
schedule:
  type: PERIOD
  period: ONCE
timeRequirements:
  time: 2
  timeUnits: minutes
intro:
  title: Demographics
  description: [
    [
      "BodyLarge",
      "In this survey we ask you to answer some questions regarding your ethnical/racial, social and economic background."
    ],
    [
      "BodyLarge",
      [
        "Italic",
        "Why is completing this survey important?"
      ]
    ],
    [
      "BodyLarge",
      "Health and disease is not only about biology. Social and economic factors can play a big role in your health. We want to account for this in our analyses and assess the impact of socioeconomic factors in the development of dysmenorrhea."
    ],
    [
      "BodyLarge",
      "You can take this survey later if you prefer. You may always choose to skip any questions that make you feel uncomfortable."
    ]
  ]
name: Demographics
sections:
  - type: survey
    key: sdh
    title: ""
    description: ""
    questions:
      - key: ms_patient
        question: Are you a patient at the Mount Sinai Health System?
        type: YESNO_CHOICE
      - key: age
        question: When is your birthday?
        type: DATE
      - key: ethnicity
        question: What is your ethnicity?
        type: SINGLE_CHOICE
        options:
          - value: hispanic_or_latino
            text: Hispanic or Latino
          - value: not_hispanic_or_latino
            text: Not Hispanic or Latino
          - value: unknown
            text: Unknown
      - key: race
        question: What is your race?
        description: Select all that apply
        type: MULTIPLE_CHOICE
        options:
          - value: american
            text: American Indian or Alaska Native
          - value: asian
            text: Asian
          - value: black
            text: Black, African-American
          - value: hawaiian
            text: Native Hawaiian or Other Pacific Islander
          - value: white
            text: White
          - value: unknown
            text: Unknown
      - key: education
        question: What is your highest level of education?
        type: SINGLE_CHOICE
        options:
          - value: no_diploma
            text: No high school diploma
          - value: high_school
            text: High school graduate
          - value: ged
            text: GED or equivalent
          - value: some_college
            text: Some college/No degree
          - value: college_degree
            text: College degree or higher
          - value: occupational
            text: Occupational, technical, or vocational program
      - key: income
        question: What is your current annual income?
        type: SINGLE_CHOICE
        options:
          - value: under_15
            text: Under $15,000
          - value: 15_24
            text: $15,000 to $24,999
          - value: 25_34
            text: $25,000 to $34,999
          - value: 35_49
            text: $35,000 to $49,999
          - value: 50_74
            text: $50,000 to $74,999
          - value: 75_99
            text: $75,000 to $99,999
          - value: 100_149
            text: $100,000 to $149,999
          - value: 150_over
            text: $150,000 and over
          - value: no_response
            text: I choose not to answer this question
      - key: income_total
        question: Which of the following best describes the total annual income of all
          members of your household?
        type: SINGLE_CHOICE
        options:
          - value: under_50
            text: Under $50,000
          - value: 50_99
            text: $50,000 to $99,999
          - value: 100_149
            text: $100,000 to $149,999
          - value: 150_199
            text: $150,000 to $199,999
          - value: 200_249
            text: $200,000 to $249,999
          - value: 250_299
            text: $250,000 to $299,999
          - value: 300_over
            text: $300,000 and over
          - value: no_response
            text: I choose not to answer this question
      - key: household_size
        question: How many family members, including yourself, do you currently live
          with?
        type: NUMERIC
        minValue: 1
        maxValue: 20
      - key: household_members
        question: Describe the individual(s) with whom you live.
        description: Select all that apply
        type: MULTIPLE_CHOICE
        options:
          - value: spouse
            text: Husband or wife
          - value: biological_child
            text: Biological son or daughter
          - value: adopted_child
            text: Adopted son or daughter
          - value: step_child
            text: Stepson or stepdaughter
          - value: sibling
            text: Brother or sister
          - value: parent
            text: Father or mother
          - value: step_parent
            text: Stepfather or stepmother
          - value: grandchild
            text: Grandchild
          - value: grandparent
            text: Grandparent
          - value: in_law_parent
            text: Parent-in-law
          - value: in_law_child
            text: Son-in-law or daughter-in-law
          - value: other_relative
            text: Other relative
          - value: roomer
            text: Roomer or boarder
          - value: roomate
            text: Housemate or roommate
          - value: partner
            text: Unmarried partner
          - value: foster_child
            text: Foster child
          - value: facility
            text: Other patient/resident in care facility
          - value: attendent
            text: Personal care attendant
          - value: other_non_relative
            text: Other non-relative
        triggers:
          - action:
              type: SHOW
            condition:
              - section: sdh
                question: household_size
                operator: ">"
                value: 1
      - key: employment
        question: What is your employment status?
        type: SINGLE_CHOICE
        options:
          - value: employed
            text: Employed with pay (part-time, full-time, self-employed)
          - value: unable_to_work
            text: Unable to work (i.e. disability, illness or other circumstances)
          - value: student
            text: Student
          - value: caregiver
            text: Taking care of house or family
          - value: unemployed
            text: Unemployed
          - value: retired
            text: Retired
      - key: unemployed_duration
        question: How long have you been unemployed?
        type: SINGLE_CHOICE
        options:
          - value: less_than_1_year
            text: Less than 1 year
          - value: more_than_1_year
            text: One or more years
        triggers:
          - action:
              type: SHOW
            condition:
              - section: sdh
                question: employment
                operator: =
                value: unemployed
      - key: state
        question: In which state do you live in?
        type: TEXT
        placeholder: e.g. NY
      - key: zipcode
        question: What is your zip code?
        type: TEXT
        placeholder: e.g. 10029
      - key: marital_status
        question: What is your marital status?
        type: SINGLE_CHOICE
        options:
          - value: single
            text: Single, never married
          - value: married
            text: Married or in a domestic partnership
          - value: divorce
            text: Separated or divorced
          - value: widowed
            text: Widowed
      - key: fb_messenger
        question: Do you regularly use Facebook Messenger?
        description: At the conclusion of this study you will have the OPTION to upload ANONYMIZED data regarding your social interactions on Facebook Messenger. 
        type: YESNO_CHOICE
      - key: whatsapp
        question: Do you regularly use WhatsApp?
        description: At the conclusion of this study you will have the OPTION to upload ANONYMIZED data regarding your social interactions on WhatsApp. 
        type: YESNO_CHOICE
