key: dona
scorable: false
schedule:
  type: PERIOD
  period: ALWAYS
timeRequirements:
  time: 15
  timeUnits: minutes
name: DONA - WIP
intro:
  title: Intro
  description: "LOREM IPSUM"
outro:
  title: Thank you!
  description: "LOREM IPSUM"
sections:
  - type: web
    key: web_dst
    pathname: dona/data-donation
    required: true
    headerShown: false
    backMode: close
    doneContent: []
    cancelContent: []