key: dona-facebook
scorable: false
schedule:
  type: PERIOD
  period: ONCE
timeRequirements:
  time: 5
  timeUnits: minutes
name: Facebook Messenger - De-identified Data Donation
intro:
  title: Intro
  description: [
    [
      "BodyLarge",
      [
        [
          "Text",
          "In this task we will ask you to share with us "
        ],
        [
          "Bold",
          "de-identified"
        ],
        [
          "Text",
          " data regarding your social interactions on Facebook Messanger (if you use it)."
        ]
      ]
    ],
    [
      "BodyLarge",
      [
        "Italic",
        "Why is donating this data important?"
      ]
    ],
    [
      "BodyLarge",
      "Having tight social bonds and a network of people that support you through hard times can be a very big help. The secondary aim of the CRAMP Study is to investigate if social interactions mediate the relationship between resilience and menstrual cramps. Using our data donation platform you will share Facebook Messanger and WhatsApp data in a completely de-identified way. We will never be able to read the content of your messages or any information regarding whom you interacted with. However, we will be able to assess some measures of your social interactions, such as the amount of messages you sent per day. This will help us understand if social interactions can improve the wellbeing of menstruating women."
    ]
  ] 
outro:
  title: Thank you!
  description: Thank you for sharing your data. 
sections:
  - type: document
    key: anonymization
    content: [
      ["H4", ["Underline", "How does de-identification work?"]],
      ["BodyLarge", "We will remove all content from your data and limit it to metadata (e.g. length and timestamp of message). Your name, as well as the names of other participants, will get replaced by random pseudonyms (eg. \"James\" → \"anonymous13\"). You may examine the de-identification of your data before uploading it to our servers."]
    ]
  - type: document
    key: can_continue
    backMode: close
    content: [
      ["H2", "Continue?"],
      ["BodyLarge", [
        ["Text", "Press "],
        ["Bold", "NEXT"],
        ["Text", " if you would like to continue with donating your de-identified Facebook Messenger data."]
      ]],
      ["BodyLarge", "On the next screen we will show you a video on how to extract and upload your data."],
      ["BodyLarge", [
        ["Text", "This task is completely optional. If you do not wish to proceed, press the "],
        ["Bold", "X"],
        ["Text", " in the upper left corner."]
      ]]
    ]
  - type: video
    key: setup-video-1
    videoId: dona-fb-messenger-1
    autoplay: true
    beginMuted: true
    controls:
      - PlayPause
      - MuteUnmute
      - Rewind
      - Forward
    resizeMode: contain
  - type: video
    key: setup-video-2
    videoId: dona-fb-messenger-2
    autoplay: true
    beginMuted: true
    controls:
      - PlayPause
      - MuteUnmute
      - Rewind
      - Forward
    resizeMode: contain
  - type: web
    key: web_dona
    pathname: /dona/data-donation?mode=facebook
    required: true
    backMode: close
    doneContent: [
      ["H2", "Uploaded!"],
      ["BodyLarge", [
        ["Text", "Please press "],
        ["Bold", "NEXT"],
        ["Text", " to continue."]
      ]]
    ]
    cancelContent: [
      ["H2", "Upload Canceled!"],
      ["BodyLarge", [
        ["Text", "No Problem. Contribution is completely optional. Please press the "],
        ["Bold", "X"],
        ["Text", " in the upper left to close this task."]
      ]]
    ]