key: dst
scorable: false
schedule:
  type: PERIOD
  period: ONCE
timeRequirements:
  time: 15
  timeUnits: minutes
name: Resilience Test
intro:
  title: Intro
  description: [
    [
      "BodyLarge",
      "In this task we will ask you to perform a short resilience test."
    ],
    [
      "BodyLarge",
      [
        "Italic",
        "Why is it important to perform this resilience test?"
      ]
    ],
    [
      "BodyLarge",
      "The CRAMP study aims to characterize the relationship between resilience and menstrual pain. This brief cognitive test is a crucial part of our study, since these results will enable us to measure your resilience."
    ]
  ]
outro:
  title: Thank you!
  description: Thank you for completing the resilience test.
sections:
  - type: document
    key: test_procedure
    content: [
      ["H3", ["Underline", "Test Procedure"]],
      ["BodyLarge", "You will perform a cognitive and verbal test consisting of two different tasks."],
      ["BodyLarge", "We will use your front camera to record you. The recordings will be used to analyze your resilience."],
      ["BodyLarge", "For this test, please make sure that you have at least 15 minutes where you will not be disturbed. Please make sure you are in front of a neutral background for video recording."],
      ["BodyLarge", "Before and after the test, we will ask a few questions."],
      ["BodyLarge", "If you feel uncomfortable or overstrained, you can cancel this test at any time by closing the app. "]
    ]
  - type: document
    key: hrv_intro
    content: [
      ["H3", ["Underline", "Heart Rate Variability"]],
      ["BodyLarge", [
        ["Text", "We want to measure you heart rate variability before and after the tasks. This is a very important measure to assess resilience. Unfortunately Apple does not allow us to start recording heart rate variability whenever we want.  We will therefore ask you to use the "],
        ["Italic", ["Bold", "Breathe"]],
        ["Text", " function within the "],
        ["Italic", ["Bold", "Mindfulness"]],
        ["Text", " app on your Apple Watch. Activating the breathing app will allow us to record your heart rate variability."]
      ]],
      ["BodyLarge", [
        ["Text", "The breathing task on you apple watch will ask you to inhale and exhale at specific times. Please, "],
        ["Bold", "DO NOT FOLLOW THE APPLE WATCH INSTRUCTIONS SINCE THIS WILL CAUSE THE RECORDING TO BE USELESS."]
      ]],
      ["BodyLarge", "Before you begin, please follow the instructions in the following video to turn off the haptic feedback (vibrations) in your Mindfulness app.  You can turn them back on after you completed this task."]
    ]
  - type: video
    key: setup-video-1
    videoId: dst-1
    autoplay: true
    beginMuted: true
    controls:
      - PlayPause
      - MuteUnmute
      - Rewind
      - Forward
    resizeMode: contain
  - type: document
    key: haptic-outro
    content: [
      ["H3", ["Underline", "Haptic Feedback"]],
      ["BodyLarge", [
        ["Text", "If you did not do it already, please deactivate the haptic feedback on your mindfulness app now and press "],
        ["Bold", "NEXT"]
      ]],
    ]
  - type: video
    key: setup-video-2-pre
    videoId: dst-2
    autoplay: true
    beginMuted: true
    controls:
      - PlayPause
      - MuteUnmute
      - Rewind
      - Forward
    resizeMode: contain
  - type: document
    key: hrv-outro-pre
    content: [
      ["H3", ["Underline", "Heart Rate Variability"]],
      ["BodyLarge", "Did you start the Breathe session as explained in this last video?"],
      ["BodyLarge", [
        ["Text", "Press "],
        ["Bold", "NEXT"],
        ["Text", " if you did, otherwise please start the Breath session now and wait until it is over to press "],
        ["Bold", "NEXT"],
        ["Text", ". Remember "],
        ["Bold", "NOT"],
        ["Text", " to follow the inhale/exhale instructions on your Apple Watch."]
      ]],
    ]
  - type: survey
    key: mood_happy_pre
    title: ""
    description: ""
    questions:
      - key: vas
        question: Your mood (happiness)
        type: V_SCALE
        hideHeader: true
        min: 0
        max: 100
        category: mood (happiness)
        ask: Please think about your mood (happiness) right now.
        scaleExplanation: 0 is unhappy, 100 is happy.
        prompt: Rate your mood (happiness).
        minLabel: Unhappy
        maxLabel: Happy
  - type: survey
    key: mood_calm_pre
    title: ""
    description: ""
    questions:
      - key: vas
        question: Your mood (calmness)
        type: V_SCALE
        hideHeader: true
        min: 0
        max: 100
        category: mood (calmness)
        ask: Please think about your mood (calmness) right now.
        scaleExplanation: 0 is excited, 100 is calm.
        prompt: Rate your mood (calmness).
        minLabel: Excited
        maxLabel: Calm
  - type: survey
    key: stress_pre
    title: ""
    description: ""
    questions:
      - key: vas
        question: Your stress
        type: V_SCALE
        hideHeader: true
        min: 0
        max: 100
        category: stress
        ask: Please think about your stress right now.
        scaleExplanation: 0 is no stress, 100 is the worst stress imaginable.
        prompt: Rate your stress.
        minLabel: No stress
        maxLabel: The worst stress imaginable
  - type: survey
    key: panas-10-pre
    title: ""
    description: This scale consists of a number of words that describe different feelings and emotions. Read each item and mark the appropriate answer. Indicate to what extent you feel this way RIGHT NOW, that is, at the present moment.
    questions:
      - key: panas_1
        question: Upset
        type: SINGLE_CHOICE
        options:
          - value: not_at_all
            text: Very slightly or not at all
            score: 1
          - value: little
            text: A little
            score: 2
          - value: moderate
            text: Moderately
            score: 3
          - value: quite_a_bit
            text: Quite a bit
            score: 4
          - value: extreme
            text: Extremely
            score: 5
      - key: panas_2
        question: Hostile
        type: SINGLE_CHOICE
        options:
          - value: not_at_all
            text: Very slightly or not at all
            score: 1
          - value: little
            text: A little
            score: 2
          - value: moderate
            text: Moderately
            score: 3
          - value: quite_a_bit
            text: Quite a bit
            score: 4
          - value: extreme
            text: Extremely
            score: 5
      - key: panas_3
        question: Alert
        type: SINGLE_CHOICE
        options:
          - value: not_at_all
            text: Very slightly or not at all
            score: 1
          - value: little
            text: A little
            score: 2
          - value: moderate
            text: Moderately
            score: 3
          - value: quite_a_bit
            text: Quite a bit
            score: 4
          - value: extreme
            text: Extremely
            score: 5
      - key: panas_4
        question: Ashamed
        type: SINGLE_CHOICE
        options:
          - value: not_at_all
            text: Very slightly or not at all
            score: 1
          - value: little
            text: A little
            score: 2
          - value: moderate
            text: Moderately
            score: 3
          - value: quite_a_bit
            text: Quite a bit
            score: 4
          - value: extreme
            text: Extremely
            score: 5
      - key: panas_5
        question: Inspired
        type: SINGLE_CHOICE
        options:
          - value: not_at_all
            text: Very slightly or not at all
            score: 1
          - value: little
            text: A little
            score: 2
          - value: moderate
            text: Moderately
            score: 3
          - value: quite_a_bit
            text: Quite a bit
            score: 4
          - value: extreme
            text: Extremely
            score: 5
      - key: panas_6
        question: Nervous
        type: SINGLE_CHOICE
        options:
          - value: not_at_all
            text: Very slightly or not at all
            score: 1
          - value: little
            text: A little
            score: 2
          - value: moderate
            text: Moderately
            score: 3
          - value: quite_a_bit
            text: Quite a bit
            score: 4
          - value: extreme
            text: Extremely
            score: 5
      - key: panas_7
        question: Determined
        type: SINGLE_CHOICE
        options:
          - value: not_at_all
            text: Very slightly or not at all
            score: 1
          - value: little
            text: A little
            score: 2
          - value: moderate
            text: Moderately
            score: 3
          - value: quite_a_bit
            text: Quite a bit
            score: 4
          - value: extreme
            text: Extremely
            score: 5
      - key: panas_8
        question: Attentive
        type: SINGLE_CHOICE
        options:
          - value: not_at_all
            text: Very slightly or not at all
            score: 1
          - value: little
            text: A little
            score: 2
          - value: moderate
            text: Moderately
            score: 3
          - value: quite_a_bit
            text: Quite a bit
            score: 4
          - value: extreme
            text: Extremely
            score: 5
      - key: panas_9
        question: Active
        type: SINGLE_CHOICE
        options:
          - value: not_at_all
            text: Very slightly or not at all
            score: 1
          - value: little
            text: A little
            score: 2
          - value: moderate
            text: Moderately
            score: 3
          - value: quite_a_bit
            text: Quite a bit
            score: 4
          - value: extreme
            text: Extremely
            score: 5
      - key: panas_10
        question: Afraid
        type: SINGLE_CHOICE
        options:
          - value: not_at_all
            text: Very slightly or not at all
            score: 1
          - value: little
            text: A little
            score: 2
          - value: moderate
            text: Moderately
            score: 3
          - value: quite_a_bit
            text: Quite a bit
            score: 4
          - value: extreme
            text: Extremely
            score: 5
  - type: web
    key: web_dst
    pathname: /publix/1/start
    search: "?batchId=1&generalMultiple"
    required: true
    headerShown: false
    backMode: close
    doneContent: [
      ["H2", "Resilience Test Complete!"],
      ["BodyLarge", [
        ["Text", "Thank you for completing the resilience test. Press "],
        ["Bold", "NEXT"],
        ["Text", " to continue with the post-test breathe session and questionnaire."]
      ]]
    ]
    cancelContent: [
      ["H2", "Resilience Test Canceled"],
      ["BodyLarge", [
        ["Text", "The resilience test has been canceled. Please close this window by pressing the "],
        ["Bold", "X"],
        ["Text", " in the upper left corner. You may come back to this task later."]
      ]]
    ]
  - type: video
    key: setup-video-3
    videoId: dst-3
    autoplay: true
    beginMuted: true
    controls:
      - PlayPause
      - MuteUnmute
      - Rewind
      - Forward
    resizeMode: contain
  - type: document
    key: hrv-outro-post
    content: [
      ["H3", ["Underline", "Heart Rate Variability"]],
      ["BodyLarge", "Did you start the Breathe session as explained in this last video?"],
      ["BodyLarge", [
        ["Text", "Press "],
        ["Bold", "NEXT"],
        ["Text", " if you did, otherwise please start the Breath session now and wait until it is over to press "],
        ["Bold", "NEXT"],
        ["Text", ". Remember "],
        ["Bold", "NOT"],
        ["Text", " to follow the inhale/exhale instructions on your Apple Watch."]
      ]],
    ]
  - type: survey
    key: mood_happy_post
    title: ""
    description: ""
    questions:
      - key: vas
        question: Your mood (happiness)
        type: V_SCALE
        hideHeader: true
        min: 0
        max: 100
        category: mood (happiness)
        ask: Please think about your mood (happiness) right now.
        scaleExplanation: 0 is unhappy, 100 is happy.
        prompt: Rate your mood (happiness).
        minLabel: Unhappy
        maxLabel: Happy
  - type: survey
    key: mood_calm_post
    title: ""
    description: ""
    questions:
      - key: vas
        question: Your mood (calmness)
        type: V_SCALE
        hideHeader: true
        min: 0
        max: 100
        category: mood (calmness)
        ask: Please think about your mood (calmness) right now.
        scaleExplanation: 0 is excited, 100 is calm.
        prompt: Rate your mood (calmness).
        minLabel: Excited
        maxLabel: Calm
  - type: survey
    key: stress_post
    title: ""
    description: ""
    questions:
      - key: vas
        question: Your stress
        type: V_SCALE
        hideHeader: true
        min: 0
        max: 100
        category: stress
        ask: Please think about your stress right now.
        scaleExplanation: 0 is no stress, 100 is the worst stress imaginable.
        prompt: Rate your stress.
        minLabel: No stress
        maxLabel: The worst stress imaginable
  - type: survey
    key: panas-10-post
    title: ""
    description: This scale consists of a number of words that describe different feelings and emotions. Read each item and mark the appropriate answer. Indicate to what extent you feel this way RIGHT NOW, that is, at the present moment.
    questions:
      - key: panas_1
        question: Upset
        type: SINGLE_CHOICE
        options:
          - value: not_at_all
            text: Very slightly or not at all
            score: 1
          - value: little
            text: A little
            score: 2
          - value: moderate
            text: Moderately
            score: 3
          - value: quite_a_bit
            text: Quite a bit
            score: 4
          - value: extreme
            text: Extremely
            score: 5
      - key: panas_2
        question: Hostile
        type: SINGLE_CHOICE
        options:
          - value: not_at_all
            text: Very slightly or not at all
            score: 1
          - value: little
            text: A little
            score: 2
          - value: moderate
            text: Moderately
            score: 3
          - value: quite_a_bit
            text: Quite a bit
            score: 4
          - value: extreme
            text: Extremely
            score: 5
      - key: panas_3
        question: Alert
        type: SINGLE_CHOICE
        options:
          - value: not_at_all
            text: Very slightly or not at all
            score: 1
          - value: little
            text: A little
            score: 2
          - value: moderate
            text: Moderately
            score: 3
          - value: quite_a_bit
            text: Quite a bit
            score: 4
          - value: extreme
            text: Extremely
            score: 5
      - key: panas_4
        question: Ashamed
        type: SINGLE_CHOICE
        options:
          - value: not_at_all
            text: Very slightly or not at all
            score: 1
          - value: little
            text: A little
            score: 2
          - value: moderate
            text: Moderately
            score: 3
          - value: quite_a_bit
            text: Quite a bit
            score: 4
          - value: extreme
            text: Extremely
            score: 5
      - key: panas_5
        question: Inspired
        type: SINGLE_CHOICE
        options:
          - value: not_at_all
            text: Very slightly or not at all
            score: 1
          - value: little
            text: A little
            score: 2
          - value: moderate
            text: Moderately
            score: 3
          - value: quite_a_bit
            text: Quite a bit
            score: 4
          - value: extreme
            text: Extremely
            score: 5
      - key: panas_6
        question: Nervous
        type: SINGLE_CHOICE
        options:
          - value: not_at_all
            text: Very slightly or not at all
            score: 1
          - value: little
            text: A little
            score: 2
          - value: moderate
            text: Moderately
            score: 3
          - value: quite_a_bit
            text: Quite a bit
            score: 4
          - value: extreme
            text: Extremely
            score: 5
      - key: panas_7
        question: Determined
        type: SINGLE_CHOICE
        options:
          - value: not_at_all
            text: Very slightly or not at all
            score: 1
          - value: little
            text: A little
            score: 2
          - value: moderate
            text: Moderately
            score: 3
          - value: quite_a_bit
            text: Quite a bit
            score: 4
          - value: extreme
            text: Extremely
            score: 5
      - key: panas_8
        question: Attentive
        type: SINGLE_CHOICE
        options:
          - value: not_at_all
            text: Very slightly or not at all
            score: 1
          - value: little
            text: A little
            score: 2
          - value: moderate
            text: Moderately
            score: 3
          - value: quite_a_bit
            text: Quite a bit
            score: 4
          - value: extreme
            text: Extremely
            score: 5
      - key: panas_9
        question: Active
        type: SINGLE_CHOICE
        options:
          - value: not_at_all
            text: Very slightly or not at all
            score: 1
          - value: little
            text: A little
            score: 2
          - value: moderate
            text: Moderately
            score: 3
          - value: quite_a_bit
            text: Quite a bit
            score: 4
          - value: extreme
            text: Extremely
            score: 5
      - key: panas_10
        question: Afraid
        type: SINGLE_CHOICE
        options:
          - value: not_at_all
            text: Very slightly or not at all
            score: 1
          - value: little
            text: A little
            score: 2
          - value: moderate
            text: Moderately
            score: 3
          - value: quite_a_bit
            text: Quite a bit
            score: 4
          - value: extreme
            text: Extremely
            score: 5
  - type: document
    key: clarification
    content: [
      ["H3", ["Underline", "Clarification"]],
      ["BodyLarge", "Thank you for performing this test."],
      ["BodyLarge", "We would like to clarify a few things: "],
      ["UnorderedList", [
        ["BodyLarge", "The purpose of this test was to induce and anlayse individual stress response only.  "],
        ["BodyLarge", [
          ["Text", "It was "],
          ["Bold", "NOT"],
          ["Text", " intedend to evaluate your cognitive and verbal performance.     "]
        ]],
        ["BodyLarge", "Therefore, the difficulty of the calculation tasks intentionally increased with time to make you fail."],
        ["BodyLarge", [
          ["Text", "The comparison with other users was "],
          ["Bold", "FAKED"],
          ["Text", " in order to induce social stress."]
        ]],
        ["BodyLarge", [
          ["Text", "The videos have "],
          ["Bold", "NOT"],
          ["Text", " been analyzed by any algorithm."]
        ]]
      ]]
    ]