key: dst
scorable: false
schedule:
  type: PERIOD
  period: ALWAYS
timeRequirements:
  time: 5
  timeUnits: minutes
name: Stress Test
intro:
  title: Test Procedure
  description: >-
    You will perform a cognitive and verbal test consisting of two different tasks.


    We will use your front camera to record you. The recordings will be used to analyse your resilience.


    For this test, please make sure that you have at least 15 minutes where you will not be disturbed. 
    Please make sure you are in front of a neutral background for video recording. 


    Before and after the test, we will ask a few questions.


    If you feel uncomfortable or overstrained, you can cancel this test at any time by closing the app. 
outro:
  title: Clarification
  description: >-
    Thank you for performing this test. 


    We would like to clarify a few things. 


    The purpose of this test was to induce and anlayse individual stress response only. 
    It was NOT intedend to evaluate your cognitive and verbal performance. 
    Therefore, the difficulty of the calculation tasks intentionally increased with time to make you fail. 
    The comparison with other users was FAKED in order to induce social stress. 
    The videos have NOT been analysed by any algorithm.
sections:
  - type: document
    key: hrv_intro
    content: [
      ["H3", ["Underline", "Heart Rate Variability"]],
      ["BodyLarge", [
        ["Text", "We want to measure you heart rate variability before and after the tasks. This is a very important measure to assess resilience. Unfortunately Apple does not allow us to start recording heart rate variability whenever we want.  We will therefore ask you to use the "],
        ["Italic", ["Bold", "Breathe"]],
        ["Text", " function within the "],
        ["Italic", ["Bold", "Mindfulness"]],
        ["Text", " app on your Apple Watch. Activating the breathing app will allow us to record your heart rate variability."]
      ]],
      ["BodyLarge", [
        ["Text", "The breathing task on you apple watch will ask you to inhale and exhale at specific times. Please, "],
        ["Bold", "DO NOT FOLLOW THE APPLE WATCH INSTRUCTIONS SINCE THIS WILL CAUSE THE RECORDING TO BE USELESS."]
      ]],
      ["BodyLarge", "Before you begin, please follow the instructions in the following video to off the haptic feedback (vibrations) in your Mindfulness app.  You can turn them back on after you completed this task."]
    ]
  - type: video
    videoId: warrior-shield::intro
    autoplay: true
    beginMuted: true
    controls:
      - PlayPause
      - MuteUnmute
      - Rewind
      - Forward
  - type: document
    key: hrv_session_0
    content: [
      ["H3", ["Underline", "Breathe Session"]],
      ["BodyLarge", [
        ["Text", "Please, start a "],
        ["Italic", "1-minute"],
        ["Text", " breathing session from your apple watch. Remember to "],
        ["Bold", "NOT FOLLOW THE INHALE/EXHALE INSTRUCTIONS"],
        ["Text", " displayed on your watch. Press "],
        ["Bold", "NEXT"],
        ["Text", " only once you have finished your recording."]
      ]]
    ]
  - type: survey
    key: section_0
    title: Questionnaire 0
    description: ""
    questions:
      - key: question_1
        question: Yes or No?
        type: YESNO_CHOICE
  - type: web
    key: section_1
    pathname: /publix/1/start
    search: "?batchId=1&generalMultiple"
    required: true
  - type: document
    key: hrv_session_1
    content: [
      ["H3", ["Underline", "Breathe Session"]],
      ["BodyLarge", [
        ["Text", "Please, start a "],
        ["Italic", "1-minute"],
        ["Text", " breathing session from your apple watch. Remember to "],
        ["Bold", "NOT FOLLOW THE INHALE/EXHALE INSTRUCTIONS"],
        ["Text", " displayed on your watch. Press "],
        ["Bold", "NEXT"],
        ["Text", " only once you have finished your recording."]
      ]]
    ]
  - type: survey
    key: section_2
    title: Questionnaire 1
    description: ""
    questions:
      - key: question_1
        question: No or Yes?
        type: YESNO_CHOICE