key: dst
scorable: false
schedule:
  type: PERIOD
  period: ALWAYS
timeRequirements:
  time: 5
  timeUnits: minutes
name: DST WIP
intro:
  title: DST
  description: This is the placeholder, work in progress task for the Digital Stress Test!
outro:
  title: Thank you!
  description: We appreciate your participation in this important study.
sections:
  - type: survey
    key: section_0
    title: Questionnaire 0
    description: ""
    questions:
      - key: question_1
        question: Yes or No?
        type: YESNO_CHOICE
  - type: web
    key: section_1
    host: google.com
    # pathname: /publix/1/start
    # search: "?batchId=1&generalMultiple"
    # required: true
  - type: survey
    key: section_2
    title: Questionnaire 1
    description: ""
    questions:
      - key: question_1
        question: No or Yes?
        type: YESNO_CHOICE