key: ema
scorable: false
schedule:
  type: PERIOD
  period: DAILY
  timeOfDay:
    - - "0600"
      - "1159"
    - - "1200"
      - "1759"
    - - "1800"
      - "2359"
timeRequirements:
  time: 30
  timeUnits: seconds
name: Pain, Stress, Mood
sections:
  - type: survey
    key: pain
    title: ""
    description: "Please think about the last 10 minutes:"
    questions:
      - key: pain_intensity
        question: "Rate your current pain intensity:"
        type: SINGLE_CHOICE
        options:
          - value: none
            text: No pain
          - value: mild
            text: Mild menstrual pain
          - value: moderate
            text: Moderate menstrual pain
          - value: severe
            text: Severe menstrual pain
          - value: other
            text: Other non-menstrual pain
      - key: stress_level
        question: "Rate your current stress level:"
        type: SINGLE_CHOICE
        options:
          - value: none
            text: No stress
          - value: mild
            text: Mild stress
          - value: moderate
            text: Moderate stress
          - value: severe
            text: Severe stress
      - key: mood_calm
        question: You currently feel
        type: SINGLE_CHOICE
        options:
          - value: calm
            text: Calm
          - value: mostly_calm
            text: More calm then excited
          - value: mostly_excited
            text: More excited then calm
          - value: excited
            text: Excited
      - key: mood_happy
        question: You currently feel
        type: SINGLE_CHOICE
        options:
          - value: calm
            text: Calm
          - value: mostly_calm
            text: More calm then excited
          - value: mostly_excited
            text: More excited then calm
          - value: excited
            text: Excited
