key: mood
active: true
scorable: false
schedule:
  type: PERIOD
  period: ONCE
timeRequirements:
  time: 30
  timeUnits: seconds
name: Mood, Stress, Arousal
sections:
  - type: survey
    key: "0"
    title: ""
    description: ""
    questions:
      - key: mood_today_happy
        question: How would you rate your overall mood today (happiness)?
        description: 0 means unhappy, 5 means happy
        type: SLIDER
        min: 0
        max: 5
        step: 1
      - key: mood_today_calm
        question: How would you rate your overall mood today (calmness)?
        description: 0 means calm, 5 means excited
        type: SLIDER
        min: 0
        max: 5
        step: 1
      - key: stress_today
        question: How would you rate your overall stress level today?
        description: 0 means no stress, 5 means worst stress imaginable
        type: SLIDER
        min: 0
        max: 5
        step: 1
