[build]
command = "npm run-script build"
publish = "dist/"

[functions]
directory = "functions"

# [[redirects]]
# from = "/api/v1/score"
# to = "/.netlify/functions/score"

[[redirects]]
from = "/index.json"
to = "/studies/index.json"
