key: devices
schedule:
  type: PERIOD
  period: ONCE
timeRequirements:
  time: 2
  timeUnits: minutes
name: Devices
intro:
  title: Devices
  description: Complete the following section to let us know where to send the
    HeartMath intervention device, and to let us know if you need an Apple
    Watch.
outro:
  title: Thank you!
  description: Once you have your devices, you must connect your Apple Watch to
    the ehive app and wear it for at least 7 days before starting the HeartMath
    intervention. We will remind you over the course of the next few weeks. Once
    you have worn the watch for at least 7 days, you will press the "start
    intervention" button in this App to start the study.
sections:
  - type: survey
    key: address
    title: Address
    description: What is the address you would like us to send the HeartMath Device?
    questions:
      - key: full_name
        question: Full Name
        type: TEXT
        required: true
      - key: street
        question: Street
        type: TEXT
        required: true
      - key: apt_floor
        question: Apt/floor
        type: TEXT
        required: false
      - key: city
        question: City
        type: TEXT
        required: true
      - key: state
        question: State
        type: TEXT
        required: true
      - key: zip
        question: Zip
        type: TEXT
        required: true
  - type: survey
    key: "0"
    title: ""
    description: ""
    questions:
      - key: apple_watch
        question: Do you have an Apple Watch Series 4, 5, or 6?
        type: YESNO_CHOICE
        required: true
      - key: apple_watch_pickup
        question: Would you prefer to pick up your watch in person at the main Mount
          Sinai Hospital campus, or have it sent to the address provided above?
        description: If you select in person pick up we will reach out to you via email
          to set up a pick up time.
        type: SINGLE_CHOICE
        required: true
        triggers:
          - action:
              type: SHOW
            condition:
              - section: "0"
                question: apple_watch
                operator: =
                value: no
        options:
          - value: yes
            text: In person pick up
          - value: no
            text: Mailed to me
      - key: notes
        question: Notes
        type: TEXTAREA
