key: report-new-information
type: task
active: true
schedule:
  type: PERIOD
  period: ALWAYS
timeRequirements:
  time: 1
  timeUnits: minutes
name: Report New Information
intro:
  title: New COVID nasal/antibody test
  description: Complete the following section if you have a new COVID test to report.
outro:
  title: New Information Complete
  description: Thank you - we have received your report!
sections:
  - type: survey
    key: covid_test
    title: ""
    description: ""
    questions:
      - key: nasal_swab
        question: "Report a new COVID-19 nasal swab test: What was the date of your
          recent COVID-19 test?"
        type: DATE
      - key: nasal_swab_results
        question: What was the result of the nasal swab test?
        type: SINGLE_CHOICE
        triggers:
          - action:
              type: SHOW
            condition:
              - section: covid_test
                question: nasal_swab
                operator: IS_SET
        options:
          - value: positive
            text: Positive
          - value: negative
            text: Negative
      - key: antibody
        question: "Report a new COVID-19 blood antibody test: What was the date of your
          recent blood antibody test?"
        type: DATE
      - key: antibody_results
        question: What was the result of the antibody test?
        type: SINGLE_CHOICE
        triggers:
          - action:
              type: SHOW
            condition:
              - section: covid_test
                question: antibody
                operator: IS_SET
        options:
          - value: positive
            text: Positive
          - value: negative
            text: Negative

