key: intervention-video-always
active: true
schedule:
  type: PERIOD
  period: ALWAYS
timeEstimate: 5
name: Intervention Help
intro:
  title: How to Wear the Devices
  description: This video tutorial is the same as the one you watched the first
    time you did the intervention. Watch it again at any time for help on how to
    wear the devices.
outro:
  title: Thank you!
  description: Thanks for watching!
sections:
  - type: video
    key: intervention-video-always
    videoId: intervention-video-always
    rate: 1
    resizeMode: contain
