key: bladder-irritants
type: task
active: true
metadata:
  instrument: Bladder Irritants | Johns Hopkins Medicine
  references:
    - https://www.hopkinsmedicine.org/johns_hopkins_bayview/_docs/medical_services/gynecology_obstetrics/bladder_irritants.pdf
schedule:
  type: PERIOD
  period: ALWAYS
timeRequirements:
  time: 3
  timeUnits: minutes
name: Bladder Irritants
short: Do you have any bladder irritants?
intro:
  title: Bladder Irritants
  description: Certain foods and drinks have been associated with worsening
    symptoms of urinary frequency, urgency, urge incontinence, or bladder pain.
    If you suffer from any of these conditions, you may wish to try eliminating
    one or more of these foods from your diet and see if your symptoms improve.
    If bladder symptoms are related to dietary factors, strict adherence to a
    diet that eliminates the food should bring marked relief in 10 days. Once
    you are feeling better, you can begin to add foods back into your diet, one
    at a time. If symptoms return, you will be able to identify the irritant. As
    you add foods back to your diet it is very important that you drink
    significant amounts of water.
outro:
  title: Thank You
  description: >-
    Low-acid fruit substitutions include apricots, papaya, pears and
    watermelon. Coffee

    drinkers can drink Kava or other lowacid instant drinks. Tea drinkers can substitute

    non-citrus herbal and sun brewed teas. Calcium carbonate co-buffered with calcium

    ascorbate can be substituted for Vitamin C. Prelief is a dietary supplement that works

    as an acid blocker for the bladder.


    Where to get more information: 

    • Overcoming Bladder Disorders by Rebecca Chalker and Christine E. Whitmore, HarperCollins, 1990 

    • You Don't Have to Live with Cystitis! By Larrian Gillespie, Avon, 1988
sections:
  - type: survey
    key: "0"
    title: ""
    description: ""
    questions:
      - key: listen
        question: Do any of the following common bladder irritants bother you?
        description: Most people are not sensitive to ALL of these products; your goal
          is to find the foods that make YOUR symptoms worse.
        type: MULTIPLE_CHOICE
        options:
          - value: alcoholic_beverages
            text: Alcoholic beverages
          - value: apples
            text: Apples and apple juice
          - value: cantaloupe
            text: Cantaloupe
          - value: carbonated_beverages
            text: Carbonated beverages
          - value: spicy_foods
            text: Chili and spicy foods
          - value: chocolate
            text: Chocolate
          - value: citrus
            text: Citrus fruit
          - value: coffee
            text: Coffee (including decaffeinated)
          - value: cranberries
            text: Cranberries and cranberry juice
          - value: grapes
            text: Grapes
          - value: guava
            text: Guava
          - value: milk_products
            text: "Milk Products: milk, cheese, cottage cheese, yogurt, ice cream"
          - value: peaches
            text: Peaches
          - value: pineapple
            text: Pineapple
          - value: plums
            text: plums
          - value: strawberries
            text: Strawberries
          - value: sweeteners
            text: Sugar especially artificial sweeteners, saccharin, aspartame, corn
              sweeteners, honey, fructose, sucrose, lactose
          - value: tea
            text: Tea
          - value: tomatoes
            text: Tomatoes and tomato juice
          - value: vitamin_b
            text: Vitamin B complex
          - value: vinegar
            text: Vinegar

