key: physical-therapy
type: task
active: true
schedule:
  type: PERIOD
  period: DAILY
timeRequirements:
  time: 1
  timeUnits: minutes
name: Physical Therapy
sections:
  - type: survey
    key: "0"
    title: ""
    description: ""
    questions:
      - key: pt_1
        question: Did you do any physical therapy exercises today as prescribed by your
          provider?
        type: YESNO_CHOICE
      - key: pt_2
        question: Please select all those you completed and the total duration you spent
          on each today.
        type: MULTIPLE_CHOICE
        options:
          - value: relaxation
            text: Relaxation
            inlineQuestion:
              key: relaxation_description
              question: Duration or repetitions
              type: TEXTAREA
          - value: strengthening_stability
            text: Strengthening/stability
            inlineQuestion:
              key: strengthening_stability_description
              question: Duration or repetitions
              type: TEXTAREA
          - value: stretching
            text: Stretching
            inlineQuestion:
              key: stretching_description
              question: Duration or repetitions
              type: TEXTAREA
          - value: other
            text: Other
            inlineQuestion:
              key: other_description
              question: Duration or repetitions
              type: TEXTAREA
        triggers:
          - action:
              type: SHOW
            condition:
              - section: "0"
                question: pt_1
                operator: =
                value: yes
      - key: pt_3
        question: Overall, how hard were you working during the exercises?
        description: A rating of 6 indicates no or minimal exertion, and 20 indicates
          maximum possible effort. For example, a rating of 11 would correspond
          to light intensity activities, and 15 would correspond to hard
          intensity activities.
        type: SLIDER
        min: 6
        max: 20
        step: 1
        triggers:
          - action:
              type: SHOW
            condition:
              - section: "0"
                question: pt_1
                operator: =
                value: yes

