key: euro-qol-eq-5d-5l
active: true
scorable: false
metadata:
  instrument: EuroQol EQ-5D Questionnaire
  references:
    - https://euroqol.org/eq-5d-instruments/eq-5d-5l-about/
schedule:
  type: PERIOD
  period: WEEKLY
timeRequirements:
  time: 2
  timeUnits: minutes
name: Quality of Life
sections:
  - type: survey
    key: "0"
    title: ""
    description: For each heading, please select the ONE option that best describes
      your health TODAY.
    questions:
      - key: mobility
        question: MOBILITY
        type: SINGLE_CHOICE
        options:
          - value: no_problem
            text: I have no problems in walking about
          - value: slight_problem
            text: I have slight problems in walking about
          - value: moderate_problem
            text: I have moderate problems in walking about
          - value: severe_problem
            text: I have severe problems in walking about
          - value: unable_to
            text: I am unable to walk about
      - key: self_care
        question: SELF-CARE
        type: SINGLE_CHOICE
        options:
          - value: no_problem
            text: I have no problems washing or dressing myself
          - value: slight_problem
            text: I have slight problems washing or dressing myself
          - value: moderate_problem
            text: I have moderate problems washing or dressing myself
          - value: severe_problem
            text: I have severe problems washing or dressing myself
          - value: unable_to
            text: I am unable to wash or dress myself
      - key: usual_activities
        question: USUAL ACTIVITIES
        description: (e.g. work, study, housework, family or leisure activities)
        type: SINGLE_CHOICE
        options:
          - value: no_problem
            text: I have no problems doing my usual activities
          - value: slight_problem
            text: I have slight problems doing my usual activities
          - value: moderate_problem
            text: I have moderate problems doing my usual activities
          - value: severe_problem
            text: I have severe problems doing my usual activities
          - value: unable_to
            text: I am unable to do my usual activities
      - key: pain_discomfort
        question: PAIN / DISCOMFORT
        type: SINGLE_CHOICE
        options:
          - value: no_pain
            text: I have no pain or discomfort
          - value: slight_pain
            text: I have slight pain or discomfort
          - value: moderate_pain
            text: I have moderate pain or discomfort
          - value: severe_pain
            text: I have severe pain or discomfort
          - value: extreme_pain
            text: I have extreme pain or discomfort
      - key: anxiety_depression
        question: ANXIETY / DEPRESSION
        type: SINGLE_CHOICE
        options:
          - value: not_anxious
            text: I am not anxious or depressed
          - value: slightly_anxious
            text: I am slightly anxious or depressed
          - value: moderate_anxious
            text: I am moderately anxious or depressed
          - value: severely_anxious
            text: I am severely anxious or depressed
          - value: extremely_anxious
            text: I am extremely anxious or depressed
  - type: survey
    key: "1"
    title: ""
    description: ""
    questions:
      - key: health_today
        question: YOUR HEALTH TODAY
        hideHeader: true
        type: V_SCALE
        category: health
