key: neuro-qol-positive-affect-and-well-being-item-bank-v1.0
type: task
active: true
scorable: true
score:
  fn: prorate-sum
  args:
    minThreshold: 0.5
metadata:
  author: Neuro-QOL
  instrument: Positive Affect and Well-Being - Item Bank
  version: "1.0"
  references: []
schedule:
  type: PERIOD
  period: MONTHLY
timeRequirements:
  time: 2
  timeUnits: minutes
name: Positive Affect & Well-being
intro:
  title: Positive Affect & Well-being
  description: Please respond to each question or statement by marking one answer
    per statement. Your answers should reflect how you felt lately.
outro:
  title: Thank you!
  description: We appreciate your participation.
sections:
  - type: survey
    key: "0"
    title: ""
    description: Please respond to each question or statement by marking one answer
      per statement. Lately...
    questions:
      - key: wellbeing
        question: I had a sense of well-being
        type: SINGLE_CHOICE
        options:
          - value: never
            text: Never
            score: 1
          - value: rarely
            text: Rarely
            score: 2
          - value: sometimes
            text: Sometimes
            score: 3
          - value: often
            text: Often
            score: 4
          - value: always
            text: Always
            score: 5
      - key: hopeful
        question: I felt hopeful
        type: SINGLE_CHOICE
        options:
          - value: never
            text: Never
            score: 1
          - value: rarely
            text: Rarely
            score: 2
          - value: sometimes
            text: Sometimes
            score: 3
          - value: often
            text: Often
            score: 4
          - value: always
            text: Always
            score: 5
      - key: satisfying
        question: My life was satisfying
        type: SINGLE_CHOICE
        options:
          - value: never
            text: Never
            score: 1
          - value: rarely
            text: Rarely
            score: 2
          - value: sometimes
            text: Sometimes
            score: 3
          - value: often
            text: Often
            score: 4
          - value: always
            text: Always
            score: 5
      - key: purpose
        question: My life had purpose
        type: SINGLE_CHOICE
        options:
          - value: never
            text: Never
            score: 1
          - value: rarely
            text: Rarely
            score: 2
          - value: sometimes
            text: Sometimes
            score: 3
          - value: often
            text: Often
            score: 4
          - value: always
            text: Always
            score: 5
      - key: meaning
        question: My life had meaning
        type: SINGLE_CHOICE
        options:
          - value: never
            text: Never
            score: 1
          - value: rarely
            text: Rarely
            score: 2
          - value: sometimes
            text: Sometimes
            score: 3
          - value: often
            text: Often
            score: 4
          - value: always
            text: Always
            score: 5
      - key: cheerful
        question: I felt cheerful
        type: SINGLE_CHOICE
        options:
          - value: never
            text: Never
            score: 1
          - value: rarely
            text: Rarely
            score: 2
          - value: sometimes
            text: Sometimes
            score: 3
          - value: often
            text: Often
            score: 4
          - value: always
            text: Always
            score: 5
      - key: worthwhile
        question: My life was worth living
        type: SINGLE_CHOICE
        options:
          - value: never
            text: Never
            score: 1
          - value: rarely
            text: Rarely
            score: 2
          - value: sometimes
            text: Sometimes
            score: 3
          - value: often
            text: Often
            score: 4
          - value: always
            text: Always
            score: 5
      - key: balance
        question: I had a sense of balance in my life
        type: SINGLE_CHOICE
        options:
          - value: never
            text: Never
            score: 1
          - value: rarely
            text: Rarely
            score: 2
          - value: sometimes
            text: Sometimes
            score: 3
          - value: often
            text: Often
            score: 4
          - value: always
            text: Always
            score: 5
      - key: interest
        question: Many areas of my life were interesting to me
        type: SINGLE_CHOICE
        options:
          - value: never
            text: Never
            score: 1
          - value: rarely
            text: Rarely
            score: 2
          - value: sometimes
            text: Sometimes
            score: 3
          - value: often
            text: Often
            score: 4
          - value: always
            text: Always
            score: 5
      - key: enjoy
        question: I was able to enjoy life
        type: SINGLE_CHOICE
        options:
          - value: never
            text: Never
            score: 1
          - value: rarely
            text: Rarely
            score: 2
          - value: sometimes
            text: Sometimes
            score: 3
          - value: often
            text: Often
            score: 4
          - value: always
            text: Always
            score: 5
      - key: sense
        question: I felt a sense of purpose in my life
        type: SINGLE_CHOICE
        options:
          - value: never
            text: Never
            score: 1
          - value: rarely
            text: Rarely
            score: 2
          - value: sometimes
            text: Sometimes
            score: 3
          - value: often
            text: Often
            score: 4
          - value: always
            text: Always
            score: 5
      - key: laugh
        question: I could laugh and see the humor in situations
        type: SINGLE_CHOICE
        options:
          - value: never
            text: Never
            score: 1
          - value: rarely
            text: Rarely
            score: 2
          - value: sometimes
            text: Sometimes
            score: 3
          - value: often
            text: Often
            score: 4
          - value: always
            text: Always
            score: 5
      - key: relax
        question: I was able to be at ease and feel relaxed
        type: SINGLE_CHOICE
        options:
          - value: never
            text: Never
            score: 1
          - value: rarely
            text: Rarely
            score: 2
          - value: sometimes
            text: Sometimes
            score: 3
          - value: often
            text: Often
            score: 4
          - value: always
            text: Always
            score: 5
      - key: lookforward
        question: I looked forward with enjoyment to upcoming events
        type: SINGLE_CHOICE
        options:
          - value: never
            text: Never
            score: 1
          - value: rarely
            text: Rarely
            score: 2
          - value: sometimes
            text: Sometimes
            score: 3
          - value: often
            text: Often
            score: 4
          - value: always
            text: Always
            score: 5
      - key: stable
        question: I felt emotionally stable
        type: SINGLE_CHOICE
        options:
          - value: never
            text: Never
            score: 1
          - value: rarely
            text: Rarely
            score: 2
          - value: sometimes
            text: Sometimes
            score: 3
          - value: often
            text: Often
            score: 4
          - value: always
            text: Always
            score: 5
      - key: lovable
        question: I felt lovable
        type: SINGLE_CHOICE
        options:
          - value: never
            text: Never
            score: 1
          - value: rarely
            text: Rarely
            score: 2
          - value: sometimes
            text: Sometimes
            score: 3
          - value: often
            text: Often
            score: 4
          - value: always
            text: Always
            score: 5
      - key: confident
        question: I felt confident
        type: SINGLE_CHOICE
        options:
          - value: never
            text: Never
            score: 1
          - value: rarely
            text: Rarely
            score: 2
          - value: sometimes
            text: Sometimes
            score: 3
          - value: often
            text: Often
            score: 4
          - value: always
            text: Always
            score: 5
      - key: good_life
        question: I had a good life
        type: SINGLE_CHOICE
        options:
          - value: never
            text: Never
            score: 1
          - value: rarely
            text: Rarely
            score: 2
          - value: sometimes
            text: Sometimes
            score: 3
          - value: often
            text: Often
            score: 4
          - value: always
            text: Always
            score: 5
      - key: peaceful
        question: My life was peaceful
        type: SINGLE_CHOICE
        options:
          - value: never
            text: Never
            score: 1
          - value: rarely
            text: Rarely
            score: 2
          - value: sometimes
            text: Sometimes
            score: 3
          - value: often
            text: Often
            score: 4
          - value: always
            text: Always
            score: 5
      - key: fullest_life
        question: I was living life to the fullest
        type: SINGLE_CHOICE
        options:
          - value: never
            text: Never
            score: 1
          - value: rarely
            text: Rarely
            score: 2
          - value: sometimes
            text: Sometimes
            score: 3
          - value: often
            text: Often
            score: 4
          - value: always
            text: Always
            score: 5
      - key: ideal_life
        question: In most ways my life was close to my ideal
        type: SINGLE_CHOICE
        options:
          - value: never
            text: Never
            score: 1
          - value: rarely
            text: Rarely
            score: 2
          - value: sometimes
            text: Sometimes
            score: 3
          - value: often
            text: Often
            score: 4
          - value: always
            text: Always
            score: 5
      - key: thought_control
        question: I had good control of my thoughts
        type: SINGLE_CHOICE
        options:
          - value: never
            text: Never
            score: 1
          - value: rarely
            text: Rarely
            score: 2
          - value: sometimes
            text: Sometimes
            score: 3
          - value: often
            text: Often
            score: 4
          - value: always
            text: Always
            score: 5
      - key: had_hope
        question: Even when things were going badly, I still had hope
        type: SINGLE_CHOICE
        options:
          - value: never
            text: Never
            score: 1
          - value: rarely
            text: Rarely
            score: 2
          - value: sometimes
            text: Sometimes
            score: 3
          - value: often
            text: Often
            score: 4
          - value: always
            text: Always
            score: 5

