key: pro-3
active: true
scorable: true
score:
  fn: pro-3
  args: {}
schedule:
  type: PERIOD
  period: WEEKLY
timeRequirements:
  time: 1
  timeUnits: minutes
name: Crohn's Assessment
intro:
  title: Crohn's Assessment
  description: We want to understand more about your symptoms yesterday. Please
    fill out this survey and let us know.
outro:
  title: Thank you!
  description: We appreciate your participation.
sections:
  - type: survey
    key: "0"
    title: ""
    description: ""
    questions:
      - key: liquid_or_soft_stools
        question: How many liquid or soft stools?
        type: NUMERIC
      - key: abdominal_pain
        question: "Rate your abdominal pain:"
        type: SINGLE_CHOICE
        options:
          - value: none
            text: None
            score: 0
          - value: mild
            text: Mild
            score: 1
          - value: moderate
            text: Moderate
            score: 2
          - value: severe
            text: Severe
            score: 3
      - key: well_being
        question: "Rate your well-being:"
        type: SINGLE_CHOICE
        options:
          - value: generally_well
            text: Generally well
            score: 0
          - value: slightly_unwell
            text: Slightly under par
            score: 1
          - value: poor
            text: Poor
            score: 2
          - value: very_poor
            text: Very poor
            score: 3
          - value: terrible
            text: Terrible
            score: 4
