key: promis-gi-belly-pain
scorable: true
score:
  fn: sum-score
  args: {}
metadata:
  author: ""
  instrument: ""
  version: ""
  references: []
schedule:
  type: PERIOD
  period: WEEKLY
timeRequirements:
  time: 1
  timeUnits: minutes
name: Belly Pain
intro:
  title: Belly Pain
  description: >-
    We want to understand more about your belly pain over the past 7
    days. Please fill out this survey and let us know. You may skip any
    questions that you are not comfortable answering.


    The surveys in this app are NOT a replacement or substitute for medical care. The answers you provide will not be used for clinical care. For any health concerns you may have, please contact your regular healthcare provider.
outro:
  title: Thank you!
  description: We appreciate your participation.
sections:
  - type: survey
    key: promis_gi_belly_pain
    title: ""
    description: "In the past 7 days:"
    questions:
      - key: pain_often
        question: How often did you have belly pain?
        type: SINGLE_CHOICE
        options:
          - value: never
            text: Never
            score: 1
          - value: one_day
            text: One day
            score: 2
          - value: 2_6_days
            text: 2-6 days
            score: 3
          - value: once_daily
            text: Once a day
            score: 4
          - value: over_once_daily
            text: More than once a day
            score: 5
      - key: pain_rating
        question: At its worst, how would you rate your belly pain?
        type: SINGLE_CHOICE
        options:
          - value: not_bad
            text: Not bad at all
            score: 1
          - value: little_bad
            text: A little bad
            score: 2
          - value: somewhat_bad
            text: Somewhat bad
            score: 3
          - value: quite_bad
            text: Quite bad
            score: 4
          - value: very_bad
            text: Very bad
            score: 5
        triggers:
          - action:
              type: SHOW
            condition:
              - section: promis_gi_belly_pain
                question: pain_often
                operator: INCLUDES
                value: one_day
              - section: promis_gi_belly_pain
                question: pain_often
                operator: INCLUDES
                value: 2_6_days
              - section: promis_gi_belly_pain
                question: pain_often
                operator: INCLUDES
                value: once_daily
              - section: promis_gi_belly_pain
                question: pain_often
                operator: INCLUDES
                value: over_once_daily
      - key: belly_pain_interfere_d2d
        question: How much did belly pain interfere with your day-to-day activities?
        type: SINGLE_CHOICE
        options:
          - value: not_at_all
            text: Not at all
            score: 1
          - value: little_bit
            text: A little bit
            score: 2
          - value: somewhat
            text: Somewhat
            score: 3
          - value: quite_bit
            text: Quite a bit
            score: 4
          - value: very_much
            text: Very much
            score: 5
        triggers:
          - action:
              type: SHOW
            condition:
              - section: promis_gi_belly_pain
                question: pain_often
                operator: INCLUDES
                value: one_day
              - section: promis_gi_belly_pain
                question: pain_often
                operator: INCLUDES
                value: 2_6_days
              - section: promis_gi_belly_pain
                question: pain_often
                operator: INCLUDES
                value: once_daily
              - section: promis_gi_belly_pain
                question: pain_often
                operator: INCLUDES
                value: over_once_daily
      - key: belly_pain_bother
        question: How much did belly pain bother you?
        type: SINGLE_CHOICE
        options:
          - value: not_at_all
            text: Not at all
            score: 1
          - value: little_bit
            text: A little bit
            score: 2
          - value: somewhat
            text: Somewhat
            score: 3
          - value: quite_bit
            text: Quite a bit
            score: 4
          - value: very_much
            text: Very much
            score: 5
        triggers:
          - action:
              type: SHOW
            condition:
              - section: promis_gi_belly_pain
                question: pain_often
                operator: INCLUDES
                value: one_day
              - section: promis_gi_belly_pain
                question: pain_often
                operator: INCLUDES
                value: 2_6_days
              - section: promis_gi_belly_pain
                question: pain_often
                operator: INCLUDES
                value: once_daily
              - section: promis_gi_belly_pain
                question: pain_often
                operator: INCLUDES
                value: over_once_daily
      - key: belly_discomfort
        question: How often did you have discomfort in your belly?
        type: SINGLE_CHOICE
        options:
          - value: never
            text: Never
            score: 1
          - value: rarely
            text: Rarely
            score: 2
          - value: sometimes
            text: Sometimes
            score: 3
          - value: often
            text: Often
            score: 4
          - value: always
            text: Always
            score: 5
