key: pss-10
scorable: true
score:
  fn: sum-score
  args: {}
metadata:
  author: ""
  instrument: PSS-10
  version: ""
  references: []
schedule:
  type: PERIOD
  period: MONTHLY
timeRequirements:
  time: 2
  timeUnits: minutes
name: Stress
intro:
  title: Stress
  description: The questions in this survey ask you about your feelings and
    thoughts during the LAST MONTH. In each case, please select your response by
    choosing the answer that represents how often you felt or thought a certain
    way.
outro:
  title: Thank you!
  description: We appreciate your participation.
sections:
  - type: survey
    key: questions
    title: ""
    description: "In the last month:"
    questions:
      - key: unexpected
        question: How often have you been upset because of something that happened
          unexpectedly?
        type: SINGLE_CHOICE
        options:
          - value: never
            text: Never
            score: 0
          - value: almost_never
            text: Almost never
            score: 1
          - value: sometimes
            text: Sometimes
            score: 2
          - value: fairly_often
            text: Fairly Often
            score: 3
          - value: very_often
            text: Very Often
            score: 4
      - key: control
        question: How often have you felt that you were unable to control the important
          things in your life?
        type: SINGLE_CHOICE
        options:
          - value: never
            text: Never
            score: 0
          - value: almost_never
            text: Almost never
            score: 1
          - value: sometimes
            text: Sometimes
            score: 2
          - value: fairly_often
            text: Fairly Often
            score: 3
          - value: very_often
            text: Very Often
            score: 4
      - key: nervous
        question: How often have you felt nervous and “stressed”?
        type: SINGLE_CHOICE
        options:
          - value: never
            text: Never
            score: 0
          - value: almost_never
            text: Almost never
            score: 1
          - value: sometimes
            text: Sometimes
            score: 2
          - value: fairly_often
            text: Fairly Often
            score: 3
          - value: very_often
            text: Very Often
            score: 4
      - key: confidence
        question: How often have you felt confident about your ability to handle your
          personal problems?
        type: SINGLE_CHOICE
        options:
          - value: never
            text: Never
            score: 4
          - value: almost_never
            text: Almost never
            score: 3
          - value: sometimes
            text: Sometimes
            score: 2
          - value: fairly_often
            text: Fairly Often
            score: 1
          - value: very_often
            text: Very Often
            score: 0
      - key: positive
        question: How often have you felt that things were going your way?
        type: SINGLE_CHOICE
        options:
          - value: never
            text: Never
            score: 4
          - value: almost_never
            text: Almost never
            score: 3
          - value: sometimes
            text: Sometimes
            score: 2
          - value: fairly_often
            text: Fairly Often
            score: 1
          - value: very_often
            text: Very Often
            score: 0
      - key: cope
        question: How often have you found that you could not cope with all the things
          that you had to do?
        type: SINGLE_CHOICE
        options:
          - value: never
            text: Never
            score: 0
          - value: almost_never
            text: Almost never
            score: 1
          - value: sometimes
            text: Sometimes
            score: 2
          - value: fairly_often
            text: Fairly Often
            score: 3
          - value: very_often
            text: Very Often
            score: 4
      - key: irritations
        question: How often have you been able to control irritations in your life?
        type: SINGLE_CHOICE
        options:
          - value: never
            text: Never
            score: 4
          - value: almost_never
            text: Almost never
            score: 3
          - value: sometimes
            text: Sometimes
            score: 2
          - value: fairly_often
            text: Fairly Often
            score: 1
          - value: very_often
            text: Very Often
            score: 0
      - key: ontop
        question: How often have you felt that you were on top of things
        type: SINGLE_CHOICE
        options:
          - value: never
            text: Never
            score: 4
          - value: almost_never
            text: Almost never
            score: 3
          - value: sometimes
            text: Sometimes
            score: 2
          - value: fairly_often
            text: Fairly Often
            score: 1
          - value: very_often
            text: Very Often
            score: 0
      - key: anger
        question: How often have you been angered because of things that were outside of
          your control?
        type: SINGLE_CHOICE
        options:
          - value: never
            text: Never
            score: 0
          - value: almost_never
            text: Almost never
            score: 1
          - value: sometimes
            text: Sometimes
            score: 2
          - value: fairly_often
            text: Fairly Often
            score: 3
          - value: very_often
            text: Very Often
            score: 4
      - key: overcome
        question: How often have you felt difficulties were piling up so high that you
          could not overcome them?
        type: SINGLE_CHOICE
        options:
          - value: never
            text: Never
            score: 0
          - value: almost_never
            text: Almost never
            score: 1
          - value: sometimes
            text: Sometimes
            score: 2
          - value: fairly_often
            text: Fairly Often
            score: 3
          - value: very_often
            text: Very Often
            score: 4
