key: daily-afternoon-pain-tracking
scorable: false
schedule:
  type: PERIOD
  period: DAILY
  timeOfDay:
    - - "1100"
      - "2359"
timeRequirements:
  time: 2
  timeUnits: minutes
name: Pain Symptoms
sections:
 - type: survey
   key: afternoon_pain
   title: ""
   description: Track your pain symptoms.
   questions:
    - key: 1b_pain
      question: Have you experienced any pain since you last tracked your pain symptoms?
      type: YESNO_CHOICE
    - key: 1b_pain_location
      question: [["Text","On the image below, "],["Underline",["Bold","select all"]],["Text"," areas of the body where you have felt pain "],["Underline",["Bold","since you last tracked your pain symptoms"]], ["Text", "."]]
      type: BODY_PAIN_MAP
      diagramType: female
      triggers:
        - action:
            type: SHOW
          condition:
            - section: morning_pain
              question: 1b_pain
              operator: =
              value: 'yes'     
    - key: 1b_pain_type
      question: Describe the pain
      type: MULTIPLE_CHOICE
      description: Select all that apply.
      triggers:
        - action:
            type: SHOW
          condition:
            - section: morning_pain
              question: 1b_pain
              operator: =
              value: 'yes'  
      options:
        - value: throbbing
          text: Throbbing
        - value: shootingue
          text: Shooting
        - value: stabbing
          text: Stabbing
        - value: sharp
          text: Sharp
        - value: cramping
          text: Cramping
        - value: gnawing
          text: Gnawing
        - value: hot-burning
          text: Hot-burning
        - value: aching
          text: Aching
        - value: heavy
          text: Heavy
        - value: tender
          text: Tender
        - value: splitting
          text: Splitting
        - value: tiring_exhausting
          text: Tiring-exhausting
        - value: sickening
          text: Sickening
        - value: fearful
          text: Fearful
        - value: punishing_cruel
          text: Punishing-cruel
        - value: pinching
          text: Pinching
        - value: tugging
          text: Tugging
        - value: dull
          text: Dull
        - value: radiating
          text: Radiating
        - value: piercing
          text: Piercing
