key: demographics
active: true
scorable: false
schedule:
  type: PERIOD
  period: ALWAYS
timeRequirements:
  time: 3
  timeUnits: minutes
intro:
  title: Demographics
  description: >-
    In this survey we ask you to answer some questions regarding your ethnical/racial, social and economical background.

    Why is completing this survey important?
    Health and disease is not only about biology. Social and economical factors can play a big role in your health. We want to account for this in our analyses and assess the impact of socioeconomical factors in the development of name: Demographics
name: Demographics
sections:
  - type: survey
    key: sdh
    title: ""
    description: ""
    questions:
      - key: ms_patient
        question: Are you a patient at the Mount Sinai Health System?
        type: YESNO_CHOICE 
      - key: age
        question: What is your age?
        type: AGE
      - key: ethnicity
        question: What is your ethnicity?
        type: SINGLE_CHOICE
        options:
          - value: hispanic_or_latino
            text: Hispanic or Latino
          - value: not_hispanic_or_latino
            text: Not Hispanic or Latino
          - value: unknown
            text: Unknown
      - key: race
        question: What is your race?
        description: Select all that apply
        type: MULTIPLE_CHOICE
        options:
          - value: american
            text: American Indian or Alaska Native
          - value: asian
            text: Asian
          - value: black
            text: Black, African-American
          - value: hawaiian
            text: Native Hawaiian or Other Pacific Islander
          - value: white
            text: White
          - value: unknown
            text: Unknown
      - key: ancestry
        question: What is your major ancestry? 
        description: Please check one
        type: SINGLE_CHOICE
        options:
          - value: scandinavian
            text: Scandinavian
          - value: british
            text: Irish / Celtic / British
          - value: othernortheuropean
            text: Other Northern European
          - value: easterneuropean
            text: Eastern European
          - value: southamerican
            text: South American
          - value: centralamerican
            text: Central American or Caribbean
          - value: african
            text: African
          - value: asian
            text: Asian
          - value: mediterranean
            text: Southern European / Mediterranean
          - value: other
            text: Other
            inlineQuestion:
              key: ancestry_other_description
              question: Please specify...
              type: TEXTAREA
          - value: dont-know
            text: Don't know
      - key: school
        question: Are you currently in school? 
        type: YESNO_CHOICE
      - key: education
        question: What is your highest level of education?
        type: SINGLE_CHOICE
        options:
          - value: no_diploma
            text: No high school diploma
          - value: high_school
            text: High school graduate
          - value: ged
            text: GED or equivalent
          - value: some_college
            text: Some college/No degree
          - value: college_degree
            text: College degree or higher
          - value: occupational
            text: Occupational, technical, or vocational program
      - key: income_self
        question: What is your current annual income?
        type: SINGLE_CHOICE
        options:
          - value: under_15
            text: Under $15,000
          - value: 15_24
            text: $15,000 to $24,999
          - value: 25_34
            text: $25,000 to $34,999
          - value: 35_49
            text: $35,000 to $49,999
          - value: 50_74
            text: $50,000 to $74,999
          - value: 75_99
            text: $75,000 to $99,999
          - value: 100_149
            text: $100,000 to $149,999
          - value: 150_over
            text: $150,000 and over
          - value: no_response
            text: I choose not to answer this question
      - key: income_total
        question: Which of the following best describes the total annual income of all
                   members of your household?
        type: SINGLE_CHOICE
        options:
          - value: under_50
            text: Under $50,000
          - value: 50_99
            text: $50,000 to $99,999
          - value: 100_149
            text: $100,000 to $149,999
          - value: 150_199
            text: $150,000 to $199,999
          - value: 200_249
            text: $200,000 to $249,999
          - value: 250_299
            text: $250,000 to $299,999
          - value: 300_over
            text: $300,000 and over
          - value: no_response
            text: I choose not to answer this question    
      - key: household_size
        question: How many family members, including yourself, do you currently live
          with?
        type: NUMERIC
        minValue: 1
        maxValue: 20
      - key: household_members
        question: Describe the individual(s) with whom you live.
        description: Select all that apply
        type: MULTIPLE_CHOICE
        options:
          - value: spouse
            text: Husband or wife
          - value: biological_child
            text: Biological son or daughter
          - value: adopted_child
            text: Adopted son or daughter
          - value: step_child
            text: Stepson or stepdaughter
          - value: sibling
            text: Brother or sister
          - value: parent
            text: Father or mother
          - value: step_parent
            text: Stepfather or stepmother
          - value: grandchild
            text: Grandchild
          - value: grandparent
            text: Grandparent
          - value: in_law_parent
            text: Parent-in-law
          - value: in_law_child
            text: Son-in-law or daughter-in-law
          - value: other_relative
            text: Other relative
          - value: roomer
            text: Roomer or boarder
          - value: roomate
            text: Housemate or roommate
          - value: partner
            text: Unmarried partner
          - value: foster_child
            text: Foster child
          - value: facility
            text: Other patient/resident in care facility
          - value: attendent
            text: Personal care attendant
          - value: other_non_relative
            text: Other non-relative
          - value: homeless
            text: N/A-Homeless
          - value: alone
            text: N/A-Alone
        triggers:
          - action:
              type: SHOW
            condition:
              - section: sdh
                question: household_size
                operator: ">="
                value: 2
  - key: employment
    question: What is your employment status?
    type: SINGLE_CHOICE
    options:
          - value: employed
            text: Employed with pay (part-time, full-time, self-employed)
          - value: unable_to_work
            text: Unable to work (i.e. disability, illness or other circumstances)
          - value: student
            text: Student
          - value: caregiver
            text: Taking care of house or family
          - value: unemployed
            text: Unemployed
          - value: retired
            text: Retired
  - key: unemployed_duration
    question: How long have you been unemployed?
    type: SINGLE_CHOICE
    options:
          - value: less_than_1_year
            text: Less than 1 year
          - value: more_than_1_year
            text: One or more years
    triggers:
          - action:
              type: SHOW
            condition:
              - section: sdh
                question: employment
                operator: =
                value: unemployed

