key: painmap
active: true
scorable: false
schedule:
  type: PERIOD
  period: ALWAYS
timeRequirements:
  time: 1
  timeUnits: minutes
name: Visual Pain Scale
sections:
  - type: survey
    key: "0"
    title: ""
    description: ""
    questions:
      - key: pain
        question: [["Text","On the image below, "],["Underline",["Bold","select all"]],["Text"," areas of the body where you have felt "],["Underline",["Bold","persistent or recurrent pain"]],["Text"," present for the last "],["Underline",["Bold","3 months on longer"]],["Text"," (chronic pain)."]]
        type: BODY_PAIN_MAP
        bodyType: female
