key: which-ibd
scorable: true
schedule:
  type: PERIOD
  period: ONCE
timeRequirements:
  time: 10
  timeUnits: seconds
name: IBD Type
sections:
  - type: survey
    key: "0"
    title: ""
    description: We need to know which type of IBD you have in order to proceed with the study.
    questions:
      - key: ibd_type
        question: Which type of IBD do you have?
        required: true
        type: SINGLE_CHOICE
        options:
          - value: crohns
            text: Crohn's Disease
          - value: ulcerative_colitis
            text: Ulcerative colitis
