key: arm
scorable: false
schedule:
  type: PERIOD
  period: NEVER
timeRequirements:
  time: 1
  timeUnits: minutes
name: Study Arm
sections:
  - type: survey
    key: content
    title: ""
    description: ""
    questions:
      - key: arm_selection
        question: Select A Study Arm
        type: SINGLE_CHOICE
        options:
          - value: case
            text: Case
          - value: control
            text: Control
