key: arm
scorable: false
schedule:
  type: PERIOD
  period: NEVER
name: Study Arm (HIDDEN DURING STUDY)
sections:
  - type: survey
    key: "0"
    title: ""
    description: ""
    questions:
      - key: arm_selection
        question: Select A Study Arm
        type: SINGLE_CHOICE
        options:
          - value: case
            text: Case
          - value: control
            text: Control
