key: begin-next-phase-app
scorable: true
score:
  fn: sum-score
  args: {}
schedule:
  type: PERIOD
  period: ALWAYS
name: Stop! Click Here Only When Instructed.
intro:
  title: Stop!
  description:
    - - H4
      - >-
        You should only continue with this task once you have reviewed your
        results in the PharMe app.
    - - BodyLarge
      - ' '
    - - H4
      - - Underline
        - Begin the next study phase.
    - - BodyLarge
      - >-
        In order to begin the next phase of the study you must have reviewed
        your results in the PharMe app. Please continue with this survey once
        you have reviewed your results.
outro:
  title: Finished
  description: >-
    Thank you for sharing. If you have reviewed your results in the PharMe app,
    you can begin the next phase of the study. If you have not, this survey will
    remain on your task list until you are ready to start.
sections:
  - type: survey
    key: '0'
    title: Stop! Only continue when instructed to do so.
    description: Answer this question to begin the next phase of the study.
    questions:
      - key: reviewed_results
        question: Have you reviewed your results in the PharMe app?
        type: SINGLE_CHOICE
        options:
          - value: yes
            text: Yes
            score: 1
          - value: no
            text: No
            score: 0
