key: lab_tests
type: task
active: true
schedule:
  type: PERIOD
  period: ALWAYS
timeRequirements:
  time: 2
  timeUnits: minutes
name: Report a new lab test
short: Enter info about your lab results
intro:
  title: Report a new lab test
  description: Let us know if you have new lab tests to share. Enter any new
    results that you have obtained since the last time you reported your lab
    tests.
outro:
  title: Report Complete
  description: Thank you! Your participation is always valued. This task will
    remain available so that you can report new lab tests at any time.
sections:
  - type: survey
    key: lab_tests
    title: ""
    description: ""
    questions:
      - key: new_test_yn
        question: Do you have a new blood test to report?
        type: MULTIPLE_CHOICE
        options:
          - value: c_reactive
            text: C-reactive protein (CRP)
          - value: erythrocyte_sr
            text: Erythrocyte sedimentation rate (ESR)
      - key: c_reactive_value
        question: What is your C-reactive protein?
        type: NUMERIC
        allowDecimals: true
        decimalPrecision: 1
        triggers:
          - action:
              type: SHOW
            condition:
              - section: lab_tests
                question: new_test_yn
                operator: INCLUDES
                value: c_reactive
      - key: c_reactive_date
        question: What is the date this blood test was drawn?
        type: DATE
        triggers:
          - action:
              type: SHOW
            condition:
              - section: lab_tests
                question: new_test_yn
                operator: INCLUDES
                value: c_reactive
      - key: erythrocyte_value
        question: What is your erythrocyte sedimentation rate (ESR)?
        type: NUMERIC
        triggers:
          - action:
              type: SHOW
            condition:
              - section: lab_tests
                question: new_test_yn
                operator: INCLUDES
                value: erythrocyte_sr
      - key: erythrocyte_date
        question: What is the date this blood test was drawn?
        type: DATE
        triggers:
          - action:
              type: SHOW
            condition:
              - section: lab_tests
                question: new_test_yn
                operator: INCLUDES
                value: erythrocyte_sr

