key: daily-check-in
schedule:
  type: PERIOD
  period: DAILY
timeRequirements:
  time: 5
  timeUnits: minutes
name: Daily Check-in
sections:
  - type: survey
    key: health_symptoms
    title: Health and Symptoms
    description: ''
    questions:
      - key: 1a
        question: '1a. Today, did you experience any pain related to your CPP condition?'
        description: Select all that apply.
        type: MULTIPLE_CHOICE
        options:
          - value: abdomen
            text: Abdomen
          - value: pelvis
            text: Pelvis
          - value: groin
            text: Groin
          - value: lower_back
            text: Lower back
          - value: hip
            text: Hip
          - value: buttocks
            text: Buttocks
          - value: inner_thigh
            text: Inner thigh
          - value: other
            text: Other
            inlineQuestion:
              key: 1a_other_description
              question: Please specify...
              type: TEXTAREA
      - key: 1a_sub_1
        question: Rate the severity of the pain.
        type: H_SCALE
        triggers:
          - action:
              type: SHOW
            condition:
              - section: health_symptoms
                question: 1a
                operator: IS_SET
        min: 1
        minLabel: None
        max: 10
        maxLabel: Worst imaginable pain
      - key: 1b
        question: 1b. Did you have to miss work or school due to your symptoms today?
        type: SINGLE_CHOICE
        options:
          - value: 'yes'
            text: 'Yes'
          - value: 'no'
            text: 'No'
          - value: n/a
            text: N/A
      - key: 1c
        question: >-
          1c. How much did pain interfere with your activities (home, social, or
          work)?
        type: SINGLE_CHOICE
        options:
          - value: not_at_all
            text: Not at all
          - value: a_little_bit
            text: A little bit
          - value: somewhat
            text: Somewhat
          - value: quite_a_bit
            text: Quite a bit
          - value: very_much
            text: Very much
      - key: '2'
        question: '2. Today, did you experience any digestive or urinary symptoms?'
        description: Select all that apply.
        type: MULTIPLE_CHOICE
        options:
          - value: heartburn
            text: Heartburn
          - value: reflux
            text: Reflux
          - value: nausea
            text: Nausea
          - value: vomiting
            text: Vomiting
          - value: indigestion
            text: Indigestion
          - value: difficulty_swallowing
            text: Difficulty swallowing
          - value: upset_stomach
            text: Upset stomach
          - value: belly_pain
            text: Belly pain
          - value: bloating
            text: Bloating
          - value: gas
            text: Gas
          - value: endo_belly
            text: Endo belly
          - value: diarrhea
            text: Loose stools/diarrhea
          - value: painful_bowel_movement
            text: Painful bowel movement
          - value: blood_in_stool
            text: Blood in stool
          - value: unable_to_urinate
            text: Unable to urinate
          - value: painful_urination
            text: Painful urination
          - value: frequent_urination
            text: Fainful urination
      - key: 2_sub_1
        question: Rate the severity of the symptom.
        type: SINGLE_CHOICE
        triggers:
          - action:
              type: SHOW
            condition:
              - section: health_symptoms
                question: '2'
                operator: IS_SET
        options:
          - value: none
            text: None
          - value: mild
            text: Mild
          - value: moderate
            text: Moderate
          - value: severe
            text: Severe
          - value: very_severe
            text: Very severe
      - key: '3'
        question: 3. How was your sleep last night?
        type: DISPLAY
      - key: 3a
        question: '3a. Refreshing:'
        type: SINGLE_CHOICE
        options:
          - value: not_at_all
            text: Not at all
          - value: a_little_bit
            text: A little bit
          - value: somewhat
            text: Somewhat
          - value: quite_a_bit
            text: Quite a bit
          - value: very_much
            text: Very much
      - key: 3b
        question: '3b. Problems with sleep:'
        type: SINGLE_CHOICE
        options:
          - value: not_at_all
            text: Not at all
          - value: a_little_bit
            text: A little bit
          - value: somewhat
            text: Somewhat
          - value: quite_a_bit
            text: Quite a bit
          - value: very_much
            text: Very much
      - key: 3c
        question: '3c. Difficulty falling asleep:'
        type: SINGLE_CHOICE
        options:
          - value: not_at_all
            text: Not at all
          - value: a_little_bit
            text: A little bit
          - value: somewhat
            text: Somewhat
          - value: quite_a_bit
            text: Quite a bit
          - value: very_much
            text: Very much
      - key: '4'
        question: 4. Do you have your period today?
        type: YESNO_CHOICE
      - key: 4_sub_1
        question: How heavy is the flow?
        type: SINGLE_CHOICE
        triggers:
          - action:
              type: SHOW
            condition:
              - section: health_symptoms
                question: '4'
                operator: =
                value: 'yes'
        options:
          - value: light_flow
            text: Light flow
          - value: medium_flow
            text: Medium flow
          - value: heavy_flow
            text: Heavy flow
      - key: 4_sub_2
        question: Are you experiencing any period related symptoms?
        description: Select all that apply.
        type: MULTIPLE_CHOICE
        triggers:
          - action:
              type: SHOW
            condition:
              - section: health_symptoms
                question: '4'
                operator: =
                value: 'yes'
        options:
          - value: dysmenorrhea
            text: Dysmenorrhea (painful menstruation)
          - value: bloating
            text: Bloating
          - value: cramps
            text: Cramps
          - value: breast_tenderness
            text: Breast tenderness
          - value: back_pain
            text: Back pain
          - value: hot_flashes
            text: Hot flashes
          - value: diarrhea
            text: Diarrhea
          - value: constipation
            text: Constipation
      - key: 4_sub_3
        question: Rate the severity of the symptoms.
        type: SINGLE_CHOICE
        triggers:
          - action:
              type: SHOW
            condition:
              - section: health_symptoms
                question: 4_sub_2
                operator: IS_SET
        options:
          - value: none
            text: None
          - value: mild
            text: Mild
          - value: moderate
            text: Moderate
          - value: severe
            text: Severe
          - value: very_severe
            text: Very severe
  - type: survey
    key: qol
    title: Your Day
    description: How was your day? Rate how today went.
    questions:
      - key: '5'
        question: '5. Would you say your quality of day is:'
        type: SINGLE_CHOICE
        options:
          - value: excellent
            text: Excellent
          - value: very_good
            text: Very good
          - value: good
            text: Good
          - value: fair
            text: Fair
          - value: poor
            text: Poor
      - key: '6'
        question: '6. How would you rate….:'
        type: DISPLAY
      - key: 6a
        question: '6a. Your physical health today:'
        type: SINGLE_CHOICE
        options:
          - value: excellent
            text: Excellent
          - value: very_good
            text: Very good
          - value: good
            text: Good
          - value: fair
            text: Fair
          - value: poor
            text: Poor
      - key: 6b
        question: '6b. Your mental health, including your mood and your ability to think:'
        type: SINGLE_CHOICE
        options:
          - value: excellent
            text: Excellent
          - value: very_good
            text: Very good
          - value: good
            text: Good
          - value: fair
            text: Fair
          - value: poor
            text: Poor
      - key: 6c
        question: '6c. Your satisfaction with your social activities and relationships:'
        type: SINGLE_CHOICE
        options:
          - value: excellent
            text: Excellent
          - value: very_good
            text: Very good
          - value: good
            text: Good
          - value: fair
            text: Fair
          - value: poor
            text: Poor
      - key: '7'
        question: >-
          7. How well were you able to carry out your usual social activities
          and roles today?
        description: >-
          Including activities at home, work and in your community,
          family/work/friend responsibilities, etc.
        type: SINGLE_CHOICE
        options:
          - value: excellent
            text: Excellent
          - value: very_good
            text: Very good
          - value: good
            text: Good
          - value: fair
            text: Fair
          - value: poor
            text: Poor
      - key: '8'
        question: >-
          8. To what extent were you able to carry out your everyday physical
          activities today?
        description: >-
          Including walking, climbing stairs, carrying groceries, moving items,
          etc.
        type: SINGLE_CHOICE
        options:
          - value: completely
            text: Completely
          - value: mostly
            text: Mostly
          - value: moderately
            text: Moderately
          - value: a_little
            text: A little
          - value: not_at_all
            text: Not at all
      - key: '9'
        question: >-
          9. How often were you bothered by emotional problems such as feeling
          anxious, depressed or irritable today?
        type: SINGLE_CHOICE
        options:
          - value: never
            text: Never
          - value: rarely
            text: Rarely
          - value: sometimes
            text: Sometimes
          - value: most_of_the_day
            text: Most of the day
          - value: all_day
            text: All day/Constantly
