key: ema-1
schedule:
  type: PERIOD
  period: MOMENTARY
  timeOfDay: [["0800", "1059"]]
  randomize: notification
  randmizationEdge: leading
  minLifetime: 1800
  maxLifetime: 1800
_extends: ema-base
