key: ema-2
schedule:
  type: PERIOD
  period: MOMENTARY
  timeOfDay: [["1100", "1359"]]
  randomize: notification
  randmizationEdge: leading
  minLifetime: 1800
  maxLifetime: 1800
_extends: ema-base
