key: ema-3
schedule:
  type: PERIOD
  period: MOMENTARY
  timeOfDay: [["1400", "1659"]]
  randomize: notification
  randmizationEdge: leading
  minLifetime: 1800
  maxLifetime: 1800
_extends: ema-base
